[package]
name = "pdf_word_extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.12"
color-eyre = "0.6.2"
once_cell = "1.19.0"
pdfium-render = "0.8.17"
regex = "1.10.3"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
